package ProfileService;


/**
* ProfileService/FoodTypeCounter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/profileservice.idl
* 15. september 2020 kl 16.57 CEST
*/

public final class FoodTypeCounter implements org.omg.CORBA.portable.IDLEntity
{
  public String foodType_id = null;
  public int foodType_timesOrdered = (int)0;

  public FoodTypeCounter ()
  {
  } // ctor

  public FoodTypeCounter (String _foodType_id, int _foodType_timesOrdered)
  {
    foodType_id = _foodType_id;
    foodType_timesOrdered = _foodType_timesOrdered;
  } // ctor

} // class FoodTypeCounter
