package ProfileService;

/**
* ProfileService/FoodTypeCounterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/profileservice.idl
* tirsdag 15. september 2020 10.08.36 sentraleuropeisk sommertid
*/

public final class FoodTypeCounterHolder implements org.omg.CORBA.portable.Streamable
{
  public ProfileService.FoodTypeCounter value = null;

  public FoodTypeCounterHolder ()
  {
  }

  public FoodTypeCounterHolder (ProfileService.FoodTypeCounter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProfileService.FoodTypeCounterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProfileService.FoodTypeCounterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProfileService.FoodTypeCounterHelper.type ();
  }

}
