package ProfileService;


/**
* ProfileService/ProfilerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/profileservice.idl
* 15. september 2020 kl 16.57 CEST
*/


/* The service interface with the methods that can be invoked remotely by clients */
abstract public class ProfilerHelper
{
  private static String  _id = "IDL:ProfileService/Profiler:1.0";

  public static void insert (org.omg.CORBA.Any a, ProfileService.Profiler that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProfileService.Profiler extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ProfileService.ProfilerHelper.id (), "Profiler");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProfileService.Profiler read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ProfilerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProfileService.Profiler value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ProfileService.Profiler narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ProfileService.Profiler)
      return (ProfileService.Profiler)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ProfileService._ProfilerStub stub = new ProfileService._ProfilerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ProfileService.Profiler unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ProfileService.Profiler)
      return (ProfileService.Profiler)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ProfileService._ProfilerStub stub = new ProfileService._ProfilerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
