package ProfileService;


/**
* ProfileService/Profiler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/profileservice.idl
* tirsdag 15. september 2020 10.08.36 sentraleuropeisk sommertid
*/


/* The service interface with the methods that can be invoked remotely by clients */
public interface Profiler extends ProfilerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Profiler
