package ProfileService;


/**
* ProfileService/ProfilerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/profileservice.idl
* 15. september 2020 kl 16.57 CEST
*/


/* The service interface with the methods that can be invoked remotely by clients */
public interface ProfilerOperations 
{

  /* Returns how many times a given restaurant had orders from all the users*/
  int getTimesOrdered (String restaurant_id);

  /* Returns how many times a given restaurant had orders from a given user*/
  int getTimesOrderedByUser (String user_id, String restaurant_id);

  /* Return a list of top three users who have ordered from the restaurant the highest number of times
      	   The list should be sorted in ascending order from the user ranked 3rd to the user ranked 1st.*/
  ProfileService.UserCounter[] getTopThreeUsersByRestaurant (String restaurant_id);

  /* Return a list of top three foods that have the highest number of orders in hte zone.
             The list should be sorted in ascending order from the food ranked 3rd to the food ranked 1st.*/
  ProfileService.FoodTypeCounter[] getTopThreeFoodTypesByZone (String zone_id);
  ProfileService.UserProfile getUserProfile (String user_id);
  ProfileService.RestaurantProfile getRestaurantProfile (String restaurant_id);
} // interface ProfilerOperations
