package ProfileService;


/**
* ProfileService/RestaurantProfileHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/profileservice.idl
* 15. september 2020 kl 16.57 CEST
*/

abstract public class RestaurantProfileHelper
{
  private static String  _id = "IDL:ProfileService/RestaurantProfile:1.0";

  public static void insert (org.omg.CORBA.Any a, ProfileService.RestaurantProfile that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProfileService.RestaurantProfile extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "restaurant_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "total_times_ordered",
            _tcOf_members0,
            null);
          _tcOf_members0 = ProfileService.UserCounterHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ProfileService.TopThreeUsersHelper.id (), "TopThreeUsers", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "top_three_users",
            _tcOf_members0,
            null);
          _tcOf_members0 = ProfileService.FoodTypeCounterHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "foodTypes",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ProfileService.RestaurantProfileHelper.id (), "RestaurantProfile", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProfileService.RestaurantProfile read (org.omg.CORBA.portable.InputStream istream)
  {
    ProfileService.RestaurantProfile value = new ProfileService.RestaurantProfile ();
    value.restaurant_id = istream.read_string ();
    value.total_times_ordered = istream.read_long ();
    value.top_three_users = ProfileService.TopThreeUsersHelper.read (istream);
    int _len0 = istream.read_long ();
    value.foodTypes = new ProfileService.FoodTypeCounter[_len0];
    for (int _o1 = 0;_o1 < value.foodTypes.length; ++_o1)
      value.foodTypes[_o1] = ProfileService.FoodTypeCounterHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProfileService.RestaurantProfile value)
  {
    ostream.write_string (value.restaurant_id);
    ostream.write_long (value.total_times_ordered);
    ProfileService.TopThreeUsersHelper.write (ostream, value.top_three_users);
    ostream.write_long (value.foodTypes.length);
    for (int _i0 = 0;_i0 < value.foodTypes.length; ++_i0)
      ProfileService.FoodTypeCounterHelper.write (ostream, value.foodTypes[_i0]);
  }

}
