package ProfileService;


/**
* ProfileService/RestaurantProfile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/profileservice.idl
* 15. september 2020 kl 16.57 CEST
*/

public final class RestaurantProfile implements org.omg.CORBA.portable.IDLEntity
{
  public String restaurant_id = null;
  public int total_times_ordered = (int)0;
  public ProfileService.UserCounter top_three_users[] = null;
  public ProfileService.FoodTypeCounter foodTypes[] = null;

  public RestaurantProfile ()
  {
  } // ctor

  public RestaurantProfile (String _restaurant_id, int _total_times_ordered, ProfileService.UserCounter[] _top_three_users, ProfileService.FoodTypeCounter[] _foodTypes)
  {
    restaurant_id = _restaurant_id;
    total_times_ordered = _total_times_ordered;
    top_three_users = _top_three_users;
    foodTypes = _foodTypes;
  } // ctor

} // class RestaurantProfile
