package ProfileService;

/**
* ProfileService/RestaurantCounterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/profileservice.idl
* 15. september 2020 kl 16.57 CEST
*/

public final class RestaurantCounterHolder implements org.omg.CORBA.portable.Streamable
{
  public ProfileService.RestaurantCounter value = null;

  public RestaurantCounterHolder ()
  {
  }

  public RestaurantCounterHolder (ProfileService.RestaurantCounter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProfileService.RestaurantCounterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProfileService.RestaurantCounterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProfileService.RestaurantCounterHelper.type ();
  }

}
