package ProfileService;


/**
* ProfileService/TopThreeUsersHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/profileservice.idl
* 15. september 2020 kl 16.57 CEST
*/

abstract public class TopThreeUsersHelper
{
  private static String  _id = "IDL:ProfileService/TopThreeUsers:1.0";

  public static void insert (org.omg.CORBA.Any a, ProfileService.UserCounter[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProfileService.UserCounter[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ProfileService.UserCounterHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ProfileService.TopThreeUsersHelper.id (), "TopThreeUsers", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProfileService.UserCounter[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ProfileService.UserCounter value[] = null;
    int _len0 = istream.read_long ();
    value = new ProfileService.UserCounter[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ProfileService.UserCounterHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProfileService.UserCounter[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ProfileService.UserCounterHelper.write (ostream, value[_i0]);
  }

}
