package ProfileService;


/**
* ProfileService/UserProfile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/profileservice.idl
* 15. september 2020 kl 16.57 CEST
*/

public final class UserProfile implements org.omg.CORBA.portable.IDLEntity
{
  public String user_id = null;
  public ProfileService.RestaurantCounter restaurants[] = null;

  public UserProfile ()
  {
  } // ctor

  public UserProfile (String _user_id, ProfileService.RestaurantCounter[] _restaurants)
  {
    user_id = _user_id;
    restaurants = _restaurants;
  } // ctor

} // class UserProfile
