package ProfileService;


/**
* ProfileService/UserCounter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/profileservice.idl
* tirsdag 15. september 2020 10.08.36 sentraleuropeisk sommertid
*/

public final class UserCounter implements org.omg.CORBA.portable.IDLEntity
{
  public String user_id = null;
  public int restaurant_timesOrdered = (int)0;

  public UserCounter ()
  {
  } // ctor

  public UserCounter (String _user_id, int _restaurant_timesOrdered)
  {
    user_id = _user_id;
    restaurant_timesOrdered = _restaurant_timesOrdered;
  } // ctor

} // class UserCounter
