package ProfileService;

/**
* ProfileService/UserProfileHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/profileservice.idl
* 15. september 2020 kl 16.57 CEST
*/

public final class UserProfileHolder implements org.omg.CORBA.portable.Streamable
{
  public ProfileService.UserProfile value = null;

  public UserProfileHolder ()
  {
  }

  public UserProfileHolder (ProfileService.UserProfile initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProfileService.UserProfileHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProfileService.UserProfileHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProfileService.UserProfileHelper.type ();
  }

}
