package ProfileService;

/**
* ProfileService/UserCounterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/profileservice.idl
* tirsdag 15. september 2020 10.08.36 sentraleuropeisk sommertid
*/

public final class UserCounterHolder implements org.omg.CORBA.portable.Streamable
{
  public ProfileService.UserCounter value = null;

  public UserCounterHolder ()
  {
  }

  public UserCounterHolder (ProfileService.UserCounter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProfileService.UserCounterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProfileService.UserCounterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProfileService.UserCounterHelper.type ();
  }

}
