/* This module defines the server interface for the Restaurant Profile Service. */
module ProfileService
{
    /* UserCounter struct in order to make list of TopThreeUsers*/
    struct UserCounter
    {
        string user_id;
        long restaurant_timesOrdered;
    };

     /* FoodTypeCounter struct in order to make list of TopThreeFoodTypes*/
    struct FoodTypeCounter
    {
        string foodType_id;
        long foodType_timesOrdered;
    };

    typedef sequence<UserCounter> TopThreeUsers;
    typedef sequence<FoodTypeCounter> TopThreeFoodTypes;

    struct RestaurantProfile
    {
        string restaurant_id;
        long total_times_ordered;
        TopThreeUsers top_three_users;
        sequence<FoodTypeCounter> foodTypes;
    };

    struct RestaurantCounter
    {
        string restaurant_id;
        long restaurant_timesOrdered;
    };

    struct UserProfile
    {
        string user_id;
        sequence<RestaurantCounter> restaurants;
    };

	/* The service interface with the methods that can be invoked remotely by clients */
  	interface Profiler
  	{
    	/* Returns how many times a given restaurant had orders from all the users*/
		long getTimesOrdered(in string restaurant_id);

    	/* Returns how many times a given restaurant had orders from a given user*/
    	long getTimesOrderedByUser(in string user_id, in string restaurant_id);

    	/* Return a list of top three users who have ordered from the restaurant the highest number of times
    	   The list should be sorted in ascending order from the user ranked 3rd to the user ranked 1st.*/
    	TopThreeUsers getTopThreeUsersByRestaurant(in string restaurant_id);

    	/* Return a list of top three foods that have the highest number of orders in hte zone.
           The list should be sorted in ascending order from the food ranked 3rd to the food ranked 1st.*/
        TopThreeFoodTypes getTopThreeFoodTypesByZone(in string zone_id);

        UserProfile getUserProfile(in string user_id);
        RestaurantProfile getRestaurantProfile (in string restaurant_id);
  	};
};
